---
- name: Apt upgrade
  ansible.builtin.apt:
    upgrade: safe

- name: Install qemu-guest-agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present

- name: Install essential tools for me
  ansible.builtin.apt:
    name:
      - vim
      - tmux
    state: present
