version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  example-job:
    docker:
      # - image: cimg/base:stable
      - image: owasp/zap2docker-stable:latest
    steps:
      - checkout
      - docker/install-docker
      - run: echo "Hello, world"
      - run: ls -R
workflows:
  example-workflow:
    jobs:
      - example-job
