version: 2.1
orbs:
  slack: circleci/slack@4.12.5
jobs:
  zap-baseline:
    docker:
      # - image: cimg/base:stable
      - image: owasp/zap2docker-stable:latest
    steps:
      - checkout
      - run: mkdir /zap/wrk
      - run: /zap/zap-baseline.py -t https://mastodon.motcha.tech  -r report.html -I
      - store_artifacts:
          path: /zap/wrk/report.html
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: store-artifact-url
          command: |
            URL="https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$(($CIRCLE_BUILD_NUM - 1))/artifacts"
            artifacts=$(curl -X GET ${URL} \
            -H "Accept: application/json" \
            --header "Circle-Token: $CIRCLE_TOKEN") # APIをたたいてレスポンス値を代入する
            artifact0=$(echo $artifacts | jq '.items[0].url') # jqコマンドでurlの文字列を取得する
            echo $artifact0
            echo $artifacts
            echo "export ARTIFACT0=$artifact0" >> $BASH_ENV # 環境変数に登録する
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "<${ARTIFACT0}>",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  zap:
    jobs:
      - zap-baseline
      - notify:
          requires:
            - zap-baseline
          context: slack-secrets
