version: 2.1
orbs:
  slack: circleci/slack@4.12.5
jobs:
  zap-baseline:
    docker:
      # - image: cimg/base:stable
      - image: owasp/zap2docker-stable:latest
    steps:
      - checkout
      - run: pwd;ls -R
      - run: mkdir /zap/wrk
      - run: /zap/zap-baseline.py -t https://mastodon.motcha.tech -w report.md | true
      - store_artifacts:
          path: /zap/wrk/report.md
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - run: export TEST="teeest"
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "aaa ${TEST}",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  zap:
    jobs:
      # - zap-baseline
      - notify:
          # requires:
          #   - zap-baseline
          context: slack-secrets
