version: 2.1
jobs:
  example-job:
    docker:
      # - image: cimg/base:stable
      - image: owasp/zap2docker-stable:latest
    steps:
      - checkout
      - run: echo "Hello, world"
      - run: ls -R
workflows:
  example-workflow:
    jobs:
      - example-job
