version: 2.1
jobs:
  zap-baseline:
    docker:
      # - image: cimg/base:stable
      - image: owasp/zap2docker-stable:latest
    steps:
      - checkout
      - run: pwd;ls -R
      - run: mkdir /zap/wrk
      - run: /zap/zap-baseline.py -t https://mastodon.motcha.tech -w report.md
      - store_artifacts:
          path: /zap/wrk/report.md
workflows:
  zap:
    jobs:
      - zap-baseline
