---
- name: Get latest release version
  ansible.builtin.uri:
    url: https://api.github.com/repos/mastodon/mastodon/releases/latest
    return_content: true
  register: mastodon_git

- name: Display latest version
  ansible.builtin.debug:
    msg: "latest release version is {{ mastodon_git.json.tag_name }}"

- name: Put docker-compose file
  ansible.builtin.template:
    src: "{{inventory_hostname}}-compose.j2"
    dest: ./mastodon/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Put .env.production file
  ansible.builtin.template:
    src: env.production.j2
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    dest: ./mastodon/.env.production
    mode: "0644"

- name: Generate Directory /etc/systemd/system/docker.service.d/
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create file /etc/systemd/system/docker.service.d/aws-credentials.conf
  ansible.builtin.template:
    src: aws-credentials.conf.j2
    dest: /etc/systemd/system/docker.service.d/aws-credentials.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Execute systemd daemon-reload
    - Restart docker.service with systemd
