---
- name: Setup for CD/CI
  hosts: github_runner
  become: false
  gather_facts: true
  roles:
    - role: github_runner
  vars:
    runner_url: "https://github.com/actions/runner/releases/download/v2.305.0/actions-runner-linux-x64-2.305.0.tar.gz"
    runner_filename: "actions-runner-linux-x64-2.305.0.tar.gz"
    repo_url: "https://github.com/stormcorgi/iac-learn"
    repo_token: "***"
