---
- name: Install Monitoring things
  hosts: all
  become: true
  gather_facts: true
  roles:
    - name: Install Monitoring things
      role: monitoring
    - name: Update docker-compose file
      role: mastodon_update_compose
