---
# yamllint disable rule:line-length
- name: Provisioning K3s Cluster Nodes
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: common
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "***"
        tailscale_args: "--netfilter-mode off"
      tags:
        - never
        - tailscale
