---
- name: Update Mastodon Containers
  hosts: mastodon
  gather_facts: true
  become: true
  roles:
    - role: mastodon_download
    - role: mastodon_update_compose
    - role: mastodon_restart
      tags:
        - mastodon_restart
        - never
