name: terraform-plan
defaults:
  run:
    working-directory: terraform
run-name: plan when terraform directory changed
on:
  push:
    branches:
      - "develop"
    paths:
      - terraform/**/*.tf
jobs:
  plan:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - id: plan
        run: terraform plan -no-color
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}