name: terraform-plan-on-proxmox
run-name: plan when terraform directory changed
on:
  push:
    branches:
      - "develop"
    paths:
      - terraform/**/*.tf
env:
  tf_actions_working_dir: terraform/proxmox
defaults:
  run:
    working-directory: ${{ env.tf_actions_working_dir }}

jobs:
  plan:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-regioin: ap-northeast-1
      - uses: hashicorp/setup-terraform@v2

      - name: terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: terraform init
        id: init
        run: terraform init
      - name: terraform plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.proxmox_api_url }}
          TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
          TF_VAR_proxmox_token: ${{ secrets.proxmox_token }}
          TF_VAR_github-runner_ciuser: ${{ secrets.ciuser}}
          TF_VAR_github-runner_cipassword: ${{ secrets.cipassword}}
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}