name: terraform-apply-on-proxmox
run-name: apply when terraform proxmox change merged
on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**/*.tf
    types:
      - closed
defaults:
  run:
    working-directory: terraform/proxmox

jobs:
  plan:
    runs-on: [self-hosted, linux]
    # for debug workflow itself with act command
    # runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ap-northeast-1
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform apply
        id: apply
        run: terraform apply -no-color -auto-approve
        continue-on-error: true
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.proxmox_api_url }}
          TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
          TF_VAR_proxmox_token: ${{ secrets.proxmox_token }}
          TF_VAR_github-runner_ciuser: ${{ secrets.ciuser}}
          TF_VAR_github-runner_cipassword: ${{ secrets.cipassword}}